name: caixa_pdv
description: "Projeto Caixa PDV com integração Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências essenciais (Adicione aqui outras que seu app use, se houver)
  cupertino_icons: ^1.0.2
  firebase_core: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
