// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45dQNYdAJ4PydbTlD9G_wyWzxDFJ9LfA',
    appId: '1:1030821394632:web:799c7a89f495ee1a1dcdfd',
    messagingSenderId: '1030821394632',
    projectId: 'caixa---dia-com-maria',
    authDomain: 'caixa---dia-com-maria.firebaseapp.com',
    storageBucket: 'caixa---dia-com-maria.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjMv1Jkg1cYmQSLo0WCAfnR-zu-npQSc',
    appId: '1:1030821394632:android:839df94a11b722ee1dcdfd',
    messagingSenderId: '1030821394632',
    projectId: 'caixa---dia-com-maria',
    storageBucket: 'caixa---dia-com-maria.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY78HxMMsBK_cmS9vASUtqxXRux10dXzM',
    appId: '1:1030821394632:ios:e12bd0c5eeacabb41dcdfd',
    messagingSenderId: '1030821394632',
    projectId: 'caixa---dia-com-maria',
    storageBucket: 'caixa---dia-com-maria.firebasestorage.app',
    iosBundleId: 'com.example.caixaPdv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY78HxMMsBK_cmS9vASUtqxXRux10dXzM',
    appId: '1:1030821394632:ios:e12bd0c5eeacabb41dcdfd',
    messagingSenderId: '1030821394632',
    projectId: 'caixa---dia-com-maria',
    storageBucket: 'caixa---dia-com-maria.firebasestorage.app',
    iosBundleId: 'com.example.caixaPdv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45dQNYdAJ4PydbTlD9G_wyWzxDFJ9LfA',
    appId: '1:1030821394632:web:18f3db2ad7f44ec91dcdfd',
    messagingSenderId: '1030821394632',
    projectId: 'caixa---dia-com-maria',
    authDomain: 'caixa---dia-com-maria.firebaseapp.com',
    storageBucket: 'caixa---dia-com-maria.firebasestorage.app',
  );
}
