name: Gerar APK do Projeto

on:
  push:
    branches:
      - main # ou o nome da sua branch principal (ex: master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Java (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar o Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.x' # Ajusta para a versão aproximada do seu Flutter

      - name: Instalar Dependências
        run: flutter pub get

      - name: Gerar o APK de Release
        run: flutter build apk --release

      - name: Disponibilizar o APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
