name: Gerar APK na Nuvem

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Baixar dependencias
        run: flutter pub get

      - name: Compilar o APK de Release
        run: flutter build apk --release

      - name: Disponibilizar o arquivo para Download
        uses: actions/upload-artifact@v4
        with:
          name: aplicativo-caixa
          path: build/app/outputs/flutter-apk/app-release.apk
